/* @__NO_SIDE_EFFECTS__ */
/**
 * Track R §R3 — `derive.rule.toAccessMatrixDoc` (graph-native).
 *
 * For each policy in the graph, walks `POLICY_TARGETS_ENTITY` /
 * `POLICY_USES_RULE` / `GUARDS_ACTION` edges to build a structured
 * access-matrix document and emits it as a single
 * `artifact.docs.access-matrix` artifact (JSON).
 *
 * The matrix is the AI-consumable contract surface from PLAN.md §0.2
 * derivation #7. It answers "who can do what?" without re-reading
 * the rule body — the structural surface is enough for the doc:
 *
 *   - One entry per policy.
 *   - For each policy: target entity, predicate rule, guarded actions.
 *   - Rule body lowering details belong to R-2 / R-3 (RLS / SQL).
 *
 * **Entirely graph-native** per PLAN.md §0.5 #8: no
 * `passCtx.options.genContext` reads, no `_bridge*` JS-object
 * lookups. Reads only `graph.nodes` (typed `PolicyNodeCustom` /
 * `EntityNodeCustom` payloads) and `graph.edges` (`GUARDS_ACTION`).
 */

import { type PassResult, type KernelGraph } from "../kernel/index.ts";
import { defineArtifact, ARTIFACT_KINDS, type Artifact } from "../kernel/artifact.ts";
import type { KernelId } from "../kernel/id.ts";
import type { GenContext } from "../core/index.ts";
import { GUARDS_ACTION_EDGE_KIND, type PolicyNodeCustom } from "../dialects/auth.ts";

const PASS_NAME = "derive.rule.toAccessMatrixDoc";
const PASS_NODE_ID = `pass:${PASS_NAME}` as KernelId<"pass">;

const POLICY_NODE_KIND_ID = "node.kind.policy";
const ACTION_NODE_KIND_ID = "node.kind.action";

type PolicyEntry = {
  readonly policy_name: string;
  readonly target_entity?: string;
  readonly predicate_rule?: string;
  readonly guarded_actions: readonly string[];
};

/** Collect the names of actions guarded by a given policy via `GUARDS_ACTION` edges. */
const guardedActionNames = (graph: KernelGraph, policyName: string): string[] => {
  const guardedRole = GUARDS_ACTION_EDGE_KIND.endpoints.find((e) => e.id.endsWith(":policy"))?.id;
  const actionRole = GUARDS_ACTION_EDGE_KIND.endpoints.find((e) => e.id.endsWith(":action"))?.id;
  if (!guardedRole || !actionRole) return [];

  const names: string[] = [];
  for (const edge of graph.edges.values()) {
    if (edge.kind.id !== GUARDS_ACTION_EDGE_KIND.id) continue;
    const policyEp = edge.endpoints.find((ep) => ep.role.id === guardedRole);
    const actionEp = edge.endpoints.find((ep) => ep.role.id === actionRole);
    if (!policyEp || !actionEp) continue;
    const policyTarget = policyEp.target as { readonly name?: unknown };
    if (typeof policyTarget.name !== "string" || policyTarget.name !== policyName) continue;
    const actionTarget = actionEp.target as {
      readonly name?: unknown;
      readonly id?: unknown;
      readonly kind?: unknown;
    };
    if (typeof actionTarget.name === "string") {
      names.push(actionTarget.name);
    } else if (actionTarget.kind === "node" && typeof actionTarget.id === "string") {
      const node = graph.nodes.get(actionTarget.id);
      if (node?.kind.id === ACTION_NODE_KIND_ID && node.name) names.push(node.name);
    }
  }
  return names;
};

/**
 * Render the policy entries as a Markdown table. Human-readable
 * companion to the JSON artifact — same data, navigable form. PLAN
 * Track F: deepen contract artifacts into target output.
 */
const renderAccessMatrixMarkdown = (entries: readonly PolicyEntry[]): string => {
  const lines: string[] = [
    "# Access Matrix",
    "",
    `Generated by \`${PASS_NAME}\`. Lists every policy in the graph, its target entity, predicate rule, and guarded actions.`,
    "",
    "| Policy | Target Entity | Predicate Rule | Guarded Actions |",
    "| --- | --- | --- | --- |",
  ];
  for (const entry of entries) {
    const actions =
      entry.guarded_actions.length > 0
        ? entry.guarded_actions.map((a) => `\`${a}\``).join(", ")
        : "_none_";
    lines.push(
      `| \`${entry.policy_name}\` | ${entry.target_entity ? `\`${entry.target_entity}\`` : "_unset_"} | ${entry.predicate_rule ? `\`${entry.predicate_rule}\`` : "_unset_"} | ${actions} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
};

/**
 * Build the access-matrix artifacts for the entire graph. Emits two
 * artifacts per pass run:
 *
 *   - `docs/access-matrix.json` — machine-readable structured form
 *     for AI agents, devtools, audit pipelines.
 *   - `docs/access-matrix.md`   — human-readable Markdown table for
 *     human reviewers, hosted docs sites, PR descriptions.
 *
 * Both artifacts share `generatedFrom` provenance so callers can
 * trace either back to the same source policies.
 */
const buildAccessMatrix = (graph: KernelGraph): readonly Artifact[] => {
  const entries: PolicyEntry[] = [];

  for (const node of graph.nodes.values()) {
    if (node.kind.id !== POLICY_NODE_KIND_ID) continue;
    const custom = node.metadata?.custom as PolicyNodeCustom | undefined;
    const policyName = node.name ?? "<unnamed-policy>";
    entries.push({
      policy_name: policyName,
      target_entity: custom?.target_entity_name,
      predicate_rule: custom?.predicate_rule_name,
      guarded_actions: guardedActionNames(graph, policyName),
    });
  }

  if (entries.length === 0) return [];

  entries.sort((a, b) => a.policy_name.localeCompare(b.policy_name));

  const matrix = {
    kind: "access-matrix" as const,
    generated_by: PASS_NAME,
    policies: entries,
  };

  const jsonArtifact = defineArtifact("artifact:access-matrix", {
    target: "docs",
    kind: ARTIFACT_KINDS.DOCS_ACCESS_MATRIX,
    path: "docs/access-matrix.json",
    content: JSON.stringify(matrix, null, 2),
    generatedBy: PASS_NODE_ID,
  });

  const markdownArtifact = defineArtifact("artifact:access-matrix:md", {
    target: "docs",
    kind: ARTIFACT_KINDS.DOCS_ACCESS_MATRIX,
    path: "docs/access-matrix.md",
    content: renderAccessMatrixMarkdown(entries),
    generatedBy: PASS_NODE_ID,
  });

  return [jsonArtifact, markdownArtifact];
};

/** Register the access-matrix-doc pass. */
export const registerAccessMatrixPass = (ctx: GenContext): void => {
  if (ctx.passRegistry.has(PASS_NAME)) return;

  ctx.passRegistry.register({ name: PASS_NAME, phase: "derive" }, (graph): PassResult => {
    const artifacts = buildAccessMatrix(graph);
    return {
      success: true,
      diagnostics: [],
      artifacts,
    };
  });
};

export const ACCESS_MATRIX_PASS = PASS_NAME;
