/**
 * UI target `ui-effect-atom-jsx` — phase 1 golden snapshot
 * (docs/revised2/ui-target-effect-atom-jsx.md §5, §6 phase 1).
 *
 * Reuses the opsdesk slice fixture (`tests/golden/opsdesk-slice/slice.ts`)
 * per the spec's own open question #5 — this is the simplest resolution
 * (no second fixture to keep in sync) and keeps this suite additive: a
 * later phase's golden test adds `views.ts`/`hydration.ts` snapshots
 * without touching this file's `keys.ts`/`atoms.ts` assertions (§6,
 * "phase n-1's files must not change content when phase n lands").
 *
 * Locks:
 *  - the exact generated file set + byte-for-byte content of
 *    `generated/effect-atom-jsx/keys.ts` and `.../atoms.ts`
 *  - the `effect-atom-jsx` version string pinned by the spec (0.5.0),
 *    read from the sibling checkout's `package.json` when present —
 *    failing loudly if it has drifted, per §5
 *  - the phase-1 diagnostics (`ui-target:conservative-invalidation`,
 *    and the always-green `ui-target:redundant-key-edge` /
 *    `ui-target:unbound-requirement` checks)
 *  - that both emitted files parse as valid TypeScript (zero syntax
 *    diagnostics from `ts.createSourceFile`) — the hermetic half of the
 *    spec's tsc-as-legalization-gate (§4); the full `tsc --noEmit`
 *    against the real `effect-atom-jsx` types is opt-in below, mirroring
 *    `GEN2_PG_CONFORMANCE` in `tests/golden/opsdesk-slice/slice.test.ts`.
 */

import { expect, test } from "vite-plus/test";
import ts from "typescript";
import { lifecycle } from "../../../src/index.ts";
import { buildOpsdeskSlice } from "../opsdesk-slice/slice.ts";
import { EFFECT_ATOM_JSX_PACKAGE } from "../../../src/dialects/targets/effect-atom-jsx/pass.ts";

const PINNED_VERSION = "0.5.0";

test("effect-atom-jsx UI target phase 1 — emits keys.ts and atoms.ts", () => {
  const slice = buildOpsdeskSlice();
  const result = lifecycle.check(slice.ctx);

  const generated = result.artifacts.filter((a) =>
    a.path?.startsWith("generated/effect-atom-jsx/"),
  );
  expect(generated.map((a) => a.path).sort()).toEqual([
    "generated/effect-atom-jsx/atoms.ts",
    "generated/effect-atom-jsx/keys.ts",
  ]);
});

test("effect-atom-jsx UI target phase 1 — golden snapshot of keys.ts", () => {
  const slice = buildOpsdeskSlice();
  const result = lifecycle.check(slice.ctx);
  const keys = result.artifacts.find((a) => a.path === "generated/effect-atom-jsx/keys.ts");
  expect(keys).toBeDefined();
  expect(keys?.language).toBe("typescript");
  expect(keys?.content).toMatchInlineSnapshot(`
  	"/**
  	 * GENERATED by \`emit.ui.effectAtomJsx.keysAndAtoms\` — do not hand-edit.
  	 * Source: docs/revised2/ui-target-effect-atom-jsx.md §2.1 (opsdesk slice, phase 1).
  	 */
  	// keys.ts

  	import { Reactivity } from "effect-atom-jsx";

  	/** Reactivity key witness for the "Incident:entity" key family. */
  	export const incidentKey = Reactivity.Key.family("incident");
  	"
  `);
});

test("effect-atom-jsx UI target phase 1 — golden snapshot of atoms.ts", () => {
  const slice = buildOpsdeskSlice();
  const result = lifecycle.check(slice.ctx);
  const atoms = result.artifacts.find((a) => a.path === "generated/effect-atom-jsx/atoms.ts");
  expect(atoms).toBeDefined();
  expect(atoms?.language).toBe("typescript");
  expect(atoms?.content).toMatchInlineSnapshot(`
  	"/**
  	 * GENERATED by \`emit.ui.effectAtomJsx.keysAndAtoms\` — do not hand-edit.
  	 * Source: docs/revised2/ui-target-effect-atom-jsx.md §2.3-2.4 (opsdesk slice, phase 1).
  	 */
  	// atoms.ts

  	import { defineMutation, defineQuery } from "effect-atom-jsx";

  	import { incidentKey } from "./keys.ts";

  	// \`IncidentApi\` is the hand-authored service this slice's query/action bodies
  	// lower to (matching the spec's §2.3/§2.4 examples). Gen2 does not yet generate
  	// service implementations for query/action function bodies (Track F work); this
  	// import is an assumed application-level seam, not a gen2 artifact.
  	import { IncidentApi } from "./incident-api.ts";

  	export const listOpenIncidentsQuery = defineQuery(() => IncidentApi.listOpen(), {
  	  key: incidentKey.key,
  	  name: "listOpenIncidents",
  	});

  	// Precision-loss note (docs/revised2/ui-target-effect-atom-jsx.md §7 open
  	// question #1): this emits the conservative static family-root key, not a
  	// \`(result) => key.child(result.id)\` resolver — see the
  	// \`ui-target:conservative-invalidation\` diagnostic for this action.
  	export const acknowledgeIncidentMutation = defineMutation(
  	  (input) => IncidentApi.acknowledge(input),
  	  {
  	    name: "acknowledgeIncident",
  	    invalidates: incidentKey.key,
  	  },
  	);
  	"
  `);
});

test("effect-atom-jsx UI target phase 1 — diagnostics", () => {
  const slice = buildOpsdeskSlice();
  const result = lifecycle.check(slice.ctx);
  const uiTargetDiagnostics = result.diagnostics
    .filter((d) => d.code.startsWith("ui-target:"))
    .map((d) => ({ code: d.code, severity: d.severity }))
    .sort((a, b) => a.code.localeCompare(b.code));

  // Always-green for this slice: no child-key nodes exist yet
  // (`ui-target:redundant-key-edge`) and no Provider/Requirement edges
  // are declared (`ui-target:unbound-requirement`), so only the
  // precision-loss info diagnostic fires.
  expect(uiTargetDiagnostics).toEqual([
    { code: "ui-target:conservative-invalidation", severity: "info" },
  ]);
});

test("effect-atom-jsx UI target phase 1 — emitted source is well-formed TypeScript", () => {
  const slice = buildOpsdeskSlice();
  const result = lifecycle.check(slice.ctx);
  const generated = result.artifacts.filter((a) =>
    a.path?.startsWith("generated/effect-atom-jsx/"),
  );
  expect(generated.length).toBeGreaterThan(0);

  for (const artifact of generated) {
    const sourceFile = ts.createSourceFile(
      artifact.path ?? "generated.ts",
      String(artifact.content),
      ts.ScriptTarget.Latest,
      /* setParentNodes */ true,
      ts.ScriptKind.TS,
    );
    // `createSourceFile` never throws on bad syntax; instead it attaches
    // `parseDiagnostics` to the returned node. Zero entries there is the
    // hermetic proxy for "this parses as valid TypeScript" without
    // needing `effect-atom-jsx`'s actual types on the TS path.
    const parseDiagnostics = (sourceFile as unknown as { parseDiagnostics?: readonly unknown[] })
      .parseDiagnostics;
    expect(parseDiagnostics ?? []).toEqual([]);
  }
});

test("effect-atom-jsx UI target — imports reference the frozen target package name", () => {
  expect(EFFECT_ATOM_JSX_PACKAGE).toBe("effect-atom-jsx");
});

/**
 * Full `tsc --noEmit` conformance against the pinned `effect-atom-jsx@0.5.0`
 * sibling checkout. Opt-in via `GEN2_UI_CONFORMANCE=1` (mirroring
 * `GEN2_PG_CONFORMANCE` in the postgres slice test) so the default `vp
 * test` run never depends on a sibling checkout existing on disk.
 *
 * When enabled: reads `~/effect-atom-jsx/package.json`, fails loudly if
 * its version has drifted from the frozen snapshot, then type-checks the
 * two emitted files (plus a hand-authored `incident-api.ts` stub
 * satisfying the assumed `IncidentApi` seam) against that checkout's
 * `node_modules`/dist types.
 */
const uiConformanceEnabled = process.env.GEN2_UI_CONFORMANCE === "1";

test.skipIf(!uiConformanceEnabled)(
  "effect-atom-jsx UI target — tsc --noEmit conformance (opt-in via GEN2_UI_CONFORMANCE=1)",
  async () => {
    const { readFileSync, mkdtempSync, writeFileSync } = await import("node:fs");
    const { tmpdir, homedir } = await import("node:os");
    const { join } = await import("node:path");
    const { execFileSync } = await import("node:child_process");

    const siblingRoot = join(homedir(), "effect-atom-jsx");
    const pkg = JSON.parse(readFileSync(join(siblingRoot, "package.json"), "utf8")) as {
      version: string;
    };
    expect(pkg.version).toBe(PINNED_VERSION);

    const slice = buildOpsdeskSlice();
    const result = lifecycle.check(slice.ctx);
    const keys = result.artifacts.find((a) => a.path === "generated/effect-atom-jsx/keys.ts");
    const atoms = result.artifacts.find((a) => a.path === "generated/effect-atom-jsx/atoms.ts");
    expect(keys?.content).toBeDefined();
    expect(atoms?.content).toBeDefined();

    const dir = mkdtempSync(join(tmpdir(), "gen2-ui-conformance-"));
    writeFileSync(join(dir, "keys.ts"), String(keys!.content), "utf8");
    writeFileSync(join(dir, "atoms.ts"), String(atoms!.content), "utf8");
    // Minimal stub satisfying the assumed `IncidentApi` seam (§2.3/§2.4) —
    // gen2 does not generate this; it is the application-level surface
    // the emitted queries/mutations call into.
    writeFileSync(
      join(dir, "incident-api.ts"),
      [
        "export const IncidentApi = {",
        "  listOpen: (): Promise<unknown[]> => Promise.resolve([]),",
        "  acknowledge: (input: unknown): Promise<unknown> => Promise.resolve(input),",
        "};",
        "",
      ].join("\n"),
      "utf8",
    );
    writeFileSync(
      join(dir, "tsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            module: "esnext",
            moduleResolution: "bundler",
            target: "es2022",
            strict: true,
            noEmit: true,
            skipLibCheck: true,
            baseUrl: dir,
            paths: { "effect-atom-jsx": [join(siblingRoot, "dist", "index.d.ts")] },
          },
          include: ["*.ts"],
        },
        null,
        2,
      ),
      "utf8",
    );

    const tscBin = join(
      siblingRoot,
      "node_modules",
      ".bin",
      process.platform === "win32" ? "tsc.cmd" : "tsc",
    );
    let output = "";
    try {
      output = execFileSync(tscBin, ["-p", join(dir, "tsconfig.json")], { cwd: dir }).toString();
    } catch (error) {
      output = (error as { stdout?: Buffer }).stdout?.toString() ?? String(error);
      throw new Error(`tsc --noEmit conformance failed:\n${output}`);
    }
    expect(output).not.toMatch(/error TS/);
  },
);
